# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scottish Enterprise Visual Style Guide
author: Graeme Laurenson
email: graeme.laurenson@scotent.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Living Style Guide for Scottish Enterprise
repository: "scotent/style-guide"
url: "https://scotent.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/se-style-guide"
github_username:  scotent

# Build settings
markdown: kramdown
theme: minima

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: pretty
highlighter: rouge
  
collections:
  buttons:
    output: true
  datas:
    output: true
  errors-validation:
    output: true
  typography:
    output: true
  page-templates:
    output: true
  elements:
    output: true
  page-patterns:
    output: true
  colour-palettes:
    output: true
  form-elements:
    output: true
  components:
    output: true
    
github: [metadata]
